/**
 * @file ManualTest.h
 * @brief 手動テストコードの定義、宣言
 * @date 2026-10-05
 */
#pragma once

 //マクロ定義

 //コンパイルできれば成功
#define ENABLE_CONST_LIST_ALLOWS_SIZE
#define ENABLE_CONST_LIST_ALLOWS_CBEGIN
#define ENABLE_CONST_LIST_ALLOWS_CEND


//コンパイルできなければ成功
//#define ENABLE_CONST_LIST_REJECTS_INSERT
//#define ENABLE_CONST_LIST_REJECTS_ERASE
//#define ENABLE_CONST_LIST_REJECTS_MUTABLE_BEGIN
//#define ENABLE_CONST_LIST_REJECTS_MUTABLE_END
//#define ENABLE_CONST_ITERATOR_REJECTS_ASSIGNMENT
//#define ENABLE_ITERATOR_REJECTS_COPY_FROM_CONST
//#define ENABLE_ITERATOR_REJECTS_ASSIGN_FROM_CONST

